package net.voidarkana.ratswithwings.client.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ModAnimationDefinitions {

    public static final AnimationDefinition WALK_BAKED = AnimationDefinition.Builder.withLength(1f).looping()
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 1f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 1.5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4583433f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.92f, 0.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 1.5f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.92f, 0.85f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(39.81f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(39.81f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, 0.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 0.24f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, -0.21f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.posVec(0f, -0.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.posVec(0f, -0.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.61f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.posVec(0f, 0.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.posVec(0f, 0.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.posVec(0f, 0.24f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.posVec(0f, -0.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.posVec(0f, -0.21f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.posVec(0f, -0.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.posVec(0f, -0.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.posVec(0f, 0.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.posVec(0f, 0.61f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.posVec(0f, 0.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 4.53f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 3.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 2.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 1.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, 0.44f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, 0f, -0.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, 0f, -2.11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, 0f, -3.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -4.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, -4.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, -4.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 0f, -4.92f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, -4.53f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 0f, -3.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 0f, -2.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 0f, -1.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 0f, -0.44f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 0f, 0.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 0f, 2.11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 0f, 3.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 0f, 4.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 0f, 4.7f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 0f, 4.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, 0f, 4.92f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 4.53f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0.42f, 4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0.82f, 3.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(1f, 2.67f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0.91f, 1.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0.57f, 0.86f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0.09f, 0.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-0.42f, 0.69f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-0.82f, 1.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-1f, 2.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-0.91f, 3.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-0.57f, 4.14f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-0.09f, 4.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.42f, 4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0.82f, 3.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(1f, 2.67f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0.91f, 1.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0.57f, 0.86f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0.09f, 0.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(-0.42f, 0.69f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(-0.82f, 1.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(-1f, 2.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(-0.91f, 3.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(-0.57f, 4.14f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(-0.09f, 4.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0.42f, 4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0.42f, -4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0.82f, -3.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(1f, -2.67f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0.91f, -1.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0.57f, -0.86f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0.09f, -0.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-0.42f, -0.69f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-0.82f, -1.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-1f, -2.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-0.91f, -3.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-0.57f, -4.14f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-0.09f, -4.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0.42f, -4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0.82f, -3.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(1f, -2.67f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0.91f, -1.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0.57f, -0.86f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0.09f, -0.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(-0.42f, -0.69f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(-0.82f, -1.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(-1f, -2.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(-0.91f, -3.35f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(-0.57f, -4.14f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(-0.09f, -4.49f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0.42f, -4.31f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tail",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(29.3f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(29.97f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(28.64f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(25.67f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(21.85f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(18.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(15.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(15.03f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(16.36f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(19.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(23.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(26.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(29.3f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(29.97f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(28.64f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(25.67f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(21.85f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(18.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(15.7f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(15.03f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(16.36f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(19.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(23.15f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(26.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(29.3f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-7.5f, 0f, -6.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-6.83f, 0f, -5.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-5f, 0f, -4.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2.5f, 0f, -2.57f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, -0.65f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(1.83f, 0f, 1.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(2.5f, 0f, 3.17f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(1.83f, 0f, 4.82f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 6.14f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-2.5f, 0f, 7.05f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-5f, 0f, 7.47f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-6.83f, 0f, 7.39f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-7.5f, 0f, 6.8f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(-6.83f, 0f, 5.75f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(-5f, 0f, 4.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(-2.5f, 0f, 2.57f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 0f, 0.65f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(1.83f, 0f, -1.3f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(2.5f, 0f, -3.17f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(1.83f, 0f, -4.82f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 0f, -6.14f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(-2.5f, 0f, -7.05f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(-5f, 0f, -7.47f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(-6.83f, 0f, -7.39f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(-7.5f, 0f, -6.8f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition FLY_BAKED = AnimationDefinition.Builder.withLength(0.5f).looping()
            .addAnimation("pigeon",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-5f, 2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-5f, 4.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-5f, 5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-5f, 4.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(-5f, 2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-5f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-5f, -4.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-5f, -5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-5f, -4.33f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-5f, -2.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(75f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(80.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(82.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(80.49f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(75f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(54.51f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(52.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(54.51f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(53.01f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(56.89f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(63.62f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(71.38f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(78.11f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(81.99f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(81.99f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(78.11f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(71.38f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(63.62f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(56.89f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(53.01f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(53.01f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(26.83f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(26.83f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(18.17f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(18.17f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(26.83f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(26.83f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(18.17f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(18.17f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1.5f, 1f, 2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-59.84f, 0f, -70.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-58.1f, 0f, -100.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-65.76f, 0f, -119.54f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-75.16f, 0f, -109.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-76.9f, 0f, -79.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(-69.24f, 0f, -60.46f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-59.84f, 0f, -70.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-58.1f, 0f, -100.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-65.76f, 0f, -119.54f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-75.16f, 0f, -109.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-76.9f, 0f, -79.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-69.24f, 0f, -60.46f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-59.84f, 0f, -70.72f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(1.5f, 1f, 2f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-59.84f, 0f, 70.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-58.1f, 0f, 100.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-65.76f, 0f, 119.54f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-75.16f, 0f, 109.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-76.9f, 0f, 79.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(-69.24f, 0f, 60.46f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-59.84f, 0f, 70.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-58.1f, 0f, 100.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-65.76f, 0f, 119.54f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-75.16f, 0f, 109.28f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-76.9f, 0f, 79.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-69.24f, 0f, 60.46f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-59.84f, 0f, 70.72f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tail",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(22.5f, -9.66f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(22.5f, -7.07f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(22.5f, -2.59f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(22.5f, 2.59f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(22.5f, 7.07f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(22.5f, 9.66f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(22.5f, 9.66f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(22.5f, 7.07f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(22.5f, 2.59f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(22.5f, -2.59f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(22.5f, -7.07f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(22.5f, -9.66f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(22.5f, -9.66f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tail",
                    new AnimationChannel(AnimationChannel.Targets.SCALE,
                            new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.scaleVec(1f, 1f, 0.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.scaleVec(1f, 1f, 1.04f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-26.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-21.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-17.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-18.67f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-23.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(-27.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-26.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-21.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-17.8f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-18.67f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-23.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-27.2f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-26.33f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition RUN_BAKED = AnimationDefinition.Builder.withLength(0.5f).looping()
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.5f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2916767f, KeyframeAnimations.posVec(0f, -0.69f, -3.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -1.25f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.5f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-8.44f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(11.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, -0.69f, -3.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -1.25f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(0f, 0.5f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leg2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(11.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.degreeVec(67.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-11.25f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, 0.24f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, -0.21f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.posVec(0f, 0.61f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.posVec(0f, 0.24f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, -0.21f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 0.16f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.posVec(0f, 0.61f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 9.06f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 0f, 5.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 0.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, -4.23f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0f, -8.19f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, 0f, -9.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, 0f, -9.06f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, 0f, -5.74f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, -0.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 4.23f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 8.19f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 0f, 9.96f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 9.06f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.5f, 0.5f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(21.73f, 66.78f, -30.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(22.67f, 77.04f, -25.79f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(23.44f, 57.76f, -22.58f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(23.27f, 28.22f, -24.29f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(22.33f, 17.96f, -29.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(21.56f, 37.24f, -32.42f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(21.73f, 66.78f, -30.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(22.67f, 77.04f, -25.79f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(23.44f, 57.76f, -22.58f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(23.27f, 28.22f, -24.29f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(22.33f, 17.96f, -29.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(21.56f, 37.24f, -32.42f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(21.73f, 66.78f, -30.71f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-0.25f, -0.5f, 0.5f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("wing2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(21.73f, -66.78f, 30.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(22.67f, -77.04f, 25.79f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(23.44f, -57.76f, 22.58f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(23.27f, -28.22f, 24.29f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(22.33f, -17.96f, 29.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(21.56f, -37.24f, 32.42f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(21.73f, -66.78f, 30.71f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(22.67f, -77.04f, 25.79f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(23.44f, -57.76f, 22.58f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(23.27f, -28.22f, 24.29f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(22.33f, -17.96f, 29.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(21.56f, -37.24f, 32.42f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(21.73f, -66.78f, 30.71f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tail",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(32.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(17.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(7.73f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(12.86f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(27.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(37.27f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(32.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(17.37f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(7.73f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(12.86f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(27.63f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(37.27f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(32.14f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-32f, 0f, -4.53f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(-28.5f, 0f, -2.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-21.5f, 0f, -0.44f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-18f, 0f, 2.11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-21.5f, 0f, 4.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(-28.5f, 0f, 4.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(-32f, 0f, 4.53f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(-28.5f, 0f, 2.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-21.5f, 0f, 0.44f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-18f, 0f, -2.11f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(-21.5f, 0f, -4.1f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(-28.5f, 0f, -4.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(-32f, 0f, -4.53f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("pigeon",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.posVec(0f, 0.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, 1.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 1.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.posVec(0f, 1.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.posVec(0f, 0.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.posVec(0f, 0.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.posVec(0f, 1.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 1.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.posVec(0f, 1.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.posVec(0f, 0.18f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0.09f, 0f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
